version: '3.8'

services:
  db:
    restart: always
    image: "postgres:12.3-alpine"
    shm_size: 1g
    mem_limit: "8g"
    mem_reservation: "4g"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  redis:
    image: "redis:alpine"
    hostname: rengine-redis
    restart: always

  celery:
    build:
      context: ./web
    image: cwavesoftware/celery:latest
    restart: always
    mem_limit: "8g"
    mem_reservation: "4g"
    entrypoint: /usr/src/app/celery-entrypoint.sh
    command: watchmedo auto-restart --recursive --pattern="*.py" --directory="/usr/src/app/reNgine/" -- celery -A reNgine worker --concurrency ${MAX_CONCURRENT_SCANS?MAX_CONCURRENT_SCANS_NOT_DEFINED} -l INFO
    volumes:
      - ./web:/usr/src/app
      - github_repos:/usr/src/github
      - wordlist:/usr/src/wordlist
      - /var/www/html/rengine/media:/usr/src/scan_results
      - gf_patterns:/root/.gf
      - nuclei_templates:/root/nuclei-templates
      - tool_config:/root/.config
      - /var/www/html/rengine/staticfiles:/usr/src/staticfiles
    environment:
      - DEBUG=${DEBUG?DEBUG_NOT_DEFINED}
      - CELERY_BROKER_URL=redis://rengine-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://rengine-redis:6379/0
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - SLACK_USER=${SLACK_USER?SLACK_USER_NOT_DEFINED}
      - SLACK_TOKEN=${SLACK_TOKEN?SLACK_TOKEN_NOT_DEFINED}
      - TZ=${TIMEZONE?TIMEZONE_NOT_DEFINED}
      - RENGINE_URL=${RENGINE_URL?RENGINE_URL_NOT_DEFINED}
    depends_on:
      - db
      - redis
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  celery-beat:
    image: cwavesoftware/celery:latest
    restart: always
    entrypoint: /usr/src/app/beat-entrypoint.sh
    command: celery -A reNgine beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - celery
    environment:
      - DEBUG=${DEBUG?DEBUG_NOT_DEFINED}
      - CELERY_BROKER_URL=redis://rengine-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://rengine-redis:6379/0
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - SLACK_USER=${SLACK_USER?SLACK_USER_NOT_DEFINED}
      - SLACK_TOKEN=${SLACK_TOKEN?SLACK_TOKEN_NOT_DEFINED}
      - TZ=${TIMEZONE?TIMEZONE_NOT_DEFINED}
      - RENGINE_URL=${RENGINE_URL?RENGINE_URL_NOT_DEFINED}
    volumes:
      - ./web:/usr/src/app
      - github_repos:/usr/src/github
      - wordlist:/usr/src/wordlist
      - /var/www/html/rengine/media:/usr/src/scan_results
      - gf_patterns:/root/.gf
      - nuclei_templates:/root/nuclei-templates
      - tool_config:/root/.config
      - /var/www/html/rengine/staticfiles:/usr/src/staticfiles

  web:
    image: cwavesoftware/celery:latest
    entrypoint: /usr/src/app/entrypoint.sh
    restart: always
    mem_limit: "8g"
    mem_reservation: "4g"
    environment:
      - DEBUG=${DEBUG?DEBUG_NOT_DEFINED}
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - SLACK_USER=${SLACK_USER?SLACK_USER_NOT_DEFINED}
      - SLACK_TOKEN=${SLACK_TOKEN?SLACK_TOKEN_NOT_DEFINED}
      - TZ=${TIMEZONE?TIMEZONE_NOT_DEFINED}
      - RENGINE_URL=${RENGINE_URL?RENGINE_URL_NOT_DEFINED}

    volumes:
      - ./web:/usr/src/app
      - github_repos:/usr/src/github
      - wordlist:/usr/src/wordlist
      - /var/www/html/rengine/media:/usr/src/scan_results
      - gf_patterns:/root/.gf
      - nuclei_templates:/root/nuclei-templates
      - tool_config:/root/.config
      - /var/www/html/rengine/staticfiles:/usr/src/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery
      - celery-beat

  # tor:
  #   image: peterdavehello/tor-socks-proxy
  #   restart: always
  #   depends_on:
  #     - web
  #   ports:
  #     - "9150:9150"
  #   hostname: tor

networks:
  default:
    name: renginenet
volumes:
  tool_config:
  postgres_data:
  gf_patterns:
  nuclei_templates:
  github_repos:
  wordlist:
